CONFIG_NAME: under-devnet
PRESET_BASE: under-devnet

DEPOSIT_CHAIN_ID: 813
DEPOSIT_NETWORK_ID: 813

# Genesis
GENESIS_FORK_VERSION: 0x20000089

# Altair
ALTAIR_FORK_EPOCH: 1
ALTAIR_FORK_VERSION: 0x20000090

# Merge
BELLATRIX_FORK_EPOCH: 2
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 100000000

# Capella
# CAPELLA_FORK_EPOCH: 3
CAPELLA_FORK_VERSION: 0x20000092

# Time parameters
SECONDS_PER_SLOT: 5
SLOTS_PER_EPOCH: 32

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 000000000000000000000000000000000000beef

# Eth1 vote
ETH1_FOLLOW_DISTANCE : 8
EPOCHS_PER_ETH1_VOTING_PERIOD : 2