CONFIG_NAME: under
PRESET_BASE: under

# Genesis
# GENESIS_FORK_VERSION: 0x20000089

# Altair
ALTAIR_FORK_EPOCH: 1
# ALTAIR_FORK_VERSION: 0x20000090

# Merge
BELLATRIX_FORK_EPOCH: 2
# BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 9223372036854775806

# Capella
# CAPELLA_FORK_EPOCH: 3
# CAPELLA_FORK_VERSION: 0x20000092

# Time parameters
SECONDS_PER_SLOT: 5
SLOTS_PER_EPOCH: 8

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 000000000000000000000000000000000000beef