name: Build Docker images with Bazel and push to Docker Hub

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      version_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      GCP_SERVICE_ACCOUNT:
        required: true
      GCP_WORKLOAD_IDENTITY_PROVIDER:
        required: true
      GCP_REMOTE_CACHE_BUCKET:
        required: true

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    container:
      image: overfoundation/bazel-cross:latest
    outputs:
      docker_tag: ${{ steps.set-docker-tag.outputs.docker_tag }}
    steps:
      - uses: actions/checkout@v4

      - uses: "google-github-actions/auth@v2"
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          create_credentials_file: true

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 390.0.0"

      - name: Git config
        run: |
          git config --global --add safe.directory /__w/chronos/chronos

      - name: Set Docker Tag
        id: set-docker-tag
        run: |
          echo "docker_tag=${{ inputs.version_name }}_${{ inputs.tag_name }}" >> $GITHUB_OUTPUT

      - name: Login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run push_images for beacon-chain
        run: |
          echo "Run push_images(beacon-chain) for ${{ steps.set-docker-tag.outputs.docker_tag }}"
          bazel run \
            //cmd/beacon-chain:push_images \
            --config=release \
            --remote_cache=https://storage.googleapis.com/${{ secrets.GCP_REMOTE_CACHE_BUCKET }}/ \
            --remote_upload_local_results \
            --google_default_credentials \
            -- \
            --tag=${{ steps.set-docker-tag.outputs.docker_tag }} \
            --repository=overfoundation/chronos-beacon-chain

      - name: Run push_images for validator
        run: |
          echo "Run push_images(validator) for ${{ steps.set-docker-tag.outputs.docker_tag }}"
          bazel run \
            //cmd/validator:push_images \
            --config=release \
            --remote_cache=https://storage.googleapis.com/${{ secrets.GCP_REMOTE_CACHE_BUCKET }}/ \
            --remote_upload_local_results \
            --google_default_credentials \
            -- \
            --tag=${{ steps.set-docker-tag.outputs.docker_tag }} \
            --repository=overfoundation/chronos-validator

      - name: Run push_images for latest
        if: ${{ inputs.tag_name == 'stable' }}
        run: |
          echo "Run push_images(latest) for ${{ steps.set-docker-tag.outputs.docker_tag }}"
          bazel run \
            //cmd/beacon-chain:push_images \
            --config=release \
            --remote_cache=https://storage.googleapis.com/${{ secrets.GCP_REMOTE_CACHE_BUCKET }}/ \
            --remote_upload_local_results \
            --google_default_credentials \
            -- \
            --tag=latest \
            --repository=overfoundation/chronos-beacon-chain

          bazel run \
            //cmd/validator:push_images \
            --config=release \
            --remote_cache=https://storage.googleapis.com/${{ secrets.GCP_REMOTE_CACHE_BUCKET }}/ \
            --remote_upload_local_results \
            --google_default_credentials \
            -- \
            --tag=latest \
            --repository=overfoundation/chronos-validator
