name: Deploy triggered with tags

on:
  push:
    tags:
        # parse names from tags {name}_v{version}
      - '*_v*'

jobs:
  extract_name:
    runs-on: [self-hosted, linux, x64]
    outputs:
      tag_name: ${{ steps.extract.outputs.tag_name }}
      version_name: ${{ steps.extract.outputs.version_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract tag name, version
        id: extract
        run: |
          tag_name="${{ github.ref_name }}"
          tag_name="${tag_name%%_v*}"
          version_name="${{ github.ref_name }}"
          version_name="v${version_name#*_v}"
          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
          echo "version_name=$version_name" >> $GITHUB_OUTPUT

  build:
    needs: extract_name
    strategy:
      matrix:
        symbol-list: [chronos_osx_amd64, chronos_osx_arm64, chronos_windows, chronos_osx_amd64_minimal, chronos_osx_arm64_minimal, chronos_windows_minimal, chronos_linux_amd64, chronos_linux_amd64_minimal, chronos_linux_arm64, chronos_linux_arm64_minimal]
    uses: ./.github/workflows/dist.upload.yml
    name: build
    with:
      build_type: ${{ matrix.symbol-list }}
      tag_name: ${{ needs.extract_name.outputs.tag_name }}
      version_name: ${{ needs.extract_name.outputs.version_name }}

  notification:
    needs: [extract_name, build]
    runs-on: [self-hosted, linux, x64]
    steps:
      - run: sh /usr/local/share/notification/chronos/over_dist_notification.sh ${{ needs.extract_name.outputs.tag_name }} ${{ needs.extract_name.outputs.version_name }}