name: Build & Deploy dist to S3

on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string
      tag_name:
        required: true
        type: string
      version_name:
        required: true
        type: string

env:
  S3_BUCKET_NAME: over-protocol-dist

permissions:
  contents: read

jobs:
  build-ubuntu:
    runs-on: [self-hosted, linux, x64]
    name: Build bazel & upload
    steps:
      - uses: actions/checkout@v3
      - name: Run build
        run: |
          sh dist/build_${{ inputs.build_type }}.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: chronos-dist-${{ github.sha }}-${{ inputs.build_type }}
          path: dist/bin
          
      - name: Upload to AWS S3
        run: |
          aws s3 cp ./dist/${{ inputs.build_type }}.zip \
          ${{ format('s3://{0}/{1}/{2}/{3}.zip',  env.S3_BUCKET_NAME, inputs.tag_name, inputs.version_name, inputs.build_type ) }} \
          --acl public-read --profile over-dist
      
      - name: Drop metadata
        run: |
          echo "<${{ format('https://{0}.s3.ap-northeast-2.amazonaws.com/{1}/{2}/{3}.zip',  env.S3_BUCKET_NAME, inputs.tag_name, inputs.version_name, inputs.build_type ) }}|${{ inputs.build_type }}>" >> /usr/local/share/notification/chronos/${{ env.S3_BUCKET_NAME }}