name: Build & Deploy dist to S3

on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string
      tag_name:
        required: true
        type: string
      version_name:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  S3_BUCKET_NAME: over-protocol-dist

permissions:
  contents: read

jobs:
  build-ubuntu:
    runs-on: [self-hosted, Linux, docker]
    name: Build bazel & upload
    steps:
      - uses: actions/checkout@v3
      - name: Set Github Token
        run: |
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/superblock-dev".insteadOf "https://github.com/superblock-dev"
      - name: Run build
        run: |
          sh dist/build_${{ inputs.build_type }}.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: chronos-dist-${{ github.sha }}-${{ inputs.build_type }}
          path: dist/bin

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: Upload to AWS S3
        run: |
          aws s3 cp ./dist/${{ inputs.build_type }}.zip \
          ${{ format('s3://{0}/{1}/{2}/{3}.zip',  env.S3_BUCKET_NAME, inputs.version_name, inputs.tag_name, inputs.build_type ) }} \
          --acl public-read
      
  drop-metadata:
    needs: [build-ubuntu]
    runs-on: [self-hosted, linux, tesseract]
    steps:
      - name: Drop metadata
        run: |
          echo "<${{ format('https://{0}.s3.ap-northeast-2.amazonaws.com/{1}/{2}/{3}.zip',  env.S3_BUCKET_NAME, inputs.version_name, inputs.tag_name, inputs.build_type ) }}|${{ inputs.build_type }}>" >> /usr/local/share/notification/chronos/${{ env.S3_BUCKET_NAME }}
