name: Unit tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  unit-tests:
    uses: ./.github/workflows/_run-test.yml
    strategy:
      matrix:
        test-target:
          [
            "//api/...",
            "//async/...",
            "//beacon-chain/...",
            "//build/...",
            "//cache/...",
            "//cmd/...",
            "//config/...",
            "//consensus-types/...",
            "//container/...",
            "//contracts/...",
            "//crypto/...",
            "//encoding/...",
            "//io/...",
            "//math/...",
            "//monitoring/...",
            "//network/...",
            "//proto/...",
            "//runtime/...",
            "//testing/...",
            "//third_party/...",
            "//time/...",
            "//tools/...",
            "//validator/...",
          ]
    with:
      test-target: ${{ matrix.test-target }}
    permissions:
      id-token: write
      contents: read
    secrets:
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
