name: Unit tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    container:
      image: overfoundation/bazel-cross:latest
    permissions:
      id-token: write # Allows the workflow to request an OIDC token
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: "google-github-actions/auth@v2"
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          create_credentials_file: true

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 390.0.0"

      - name: Git config
        run: |
          git config --global --add safe.directory /__w/chronos/chronos

      - name: Run unit tests
        run: |
          bazel test \
            --config=remote-cache \
            --config=unit-test \
            -- \
            //...
