name: Unit tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    container:
      image: overfoundation/bazel-cross:latest
    permissions:
      id-token: write # Allows the workflow to request an OIDC token
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Free unused disk space
        shell: bash
        run: |
          # dh - disk usage
          df -h

          # delete packages
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y '^temurin-.*'
          sudo apt-get remove -y '^mysql-server-core-.*'
          sudo apt-get remove -y '^postgresql-.*'
          sudo apt-get remove -y azure-cli google-chrome-stable google-cloud-cli firefox powershell microsoft-edge-stable mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean

          # delete directories
          sudo rm -rf /usr/share/dotnet/
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/share/miniconda
          sudo rm -rf /usr/local/graalvm/
          sudo rm -rf /usr/local/.ghcup/
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/lib/node_modules

      - uses: "google-github-actions/auth@v2"
        with:
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          create_credentials_file: true

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 390.0.0"

      - name: Git config
        run: |
          git config --global --add safe.directory /__w/chronos/chronos

      - name: Run unit tests
        run: |
          bazel test \
            --config=remote-cache \
            --config=unit-test \
            -- \
            //...
