name: Unit tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  beacon-chain-tests:
    uses: ./.github/workflows/_run-test.yml
    with:
      test-target: "//beacon-chain/..."
    permissions:
      id-token: write
      contents: read
    secrets:
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

  other-tests:
    uses: ./.github/workflows/_run-test.yml
    with:
      test-target: "//... -//beacon-chain/..."
    permissions:
      id-token: write
      contents: read
    secrets:
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
